// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ocaml_shadow
//# shape: Ocaml_shadow:[[]]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    Do_not_use_directly = [0],
    Ocaml_shadow = [0, Do_not_use_directly];
   runtime.caml_register_global(0, Ocaml_shadow, "Ocaml_shadow");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib2NhbWxfc2hhZG93LmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6OSwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJvY2FtbF9zaGFkb3cuY21hLmpzIiwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSJdLCJuYW1lcyI6WyJydW50aW1lIiwiRG9fbm90X3VzZV9kaXJlY3RseSIsIk9jYW1sX3NoYWRvdyJdLCJtYXBwaW5ncyI6IklBQUFBLFVBQUE7QUFBQSxJQUFBQyxzQkFBQTtBQUFBLElBQUFDLGVBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
